[window]
opacity = 0.9

padding = { x = 10, y = 10}

[font]
normal = { family = "Fira Code", style = "Regular" }
size = 13

[colors]
  primary = { background = '#1d2021', foreground = '#d4be98', dim_foreground = '#928374' }

  [colors.normal]
    black   = '#32302f'
    red     = '#ea6962'
    green   = '#a9b665'
    yellow  = '#d8a657'
    blue    = '#7daea3'
    magenta = '#d3869b'
    cyan    = '#89b482'
    white   = '#d4be98'

  [colors.bright]
    black   = '#32302f'
    red     = '#ea6962'
    green   = '#a9b665'
    yellow  = '#d8a657'
    blue    = '#7daea3'
    magenta = '#d3869b'
    cyan    = '#89b482'
    white   = '#d4be98'

